<?php

$viewsDir = __DIR__ . '/resources/views';
$appDir = __DIR__ . '/app';

$replacements = [
    // --- EXACT BLADE TAG MATCHES ---
    '>Permintaan Material<' => '>Purchase Requirement<',
    '>Permintaan<' => '>Requirement<',
    '>Penawaran<' => '>Quotation<',
    '>Klaim Material<' => '>Material Claim<',
    '>Inspeksi QC<' => '>QC Inspection<',
    '>Pengumuman<' => '>Announcement<',
    '>Kurs<' => '>Exchange Rate<',
    '>Riwayat Harga<' => '>Price History<',
    '>Perbandingan Harga<' => '>Price Comparison<',
    '>Aksi<' => '>Action<',
    '>Status<' => '>Status<',
    '>Tanggal<' => '>Date<',
    '>Bulan<' => '>Month<',
    '>Tahun<' => '>Year<',
    '>Deskripsi<' => '>Description<',
    '>Catatan<' => '>Notes<',
    '>Jumlah<' => '>Amount<',
    '>Total<' => '>Total<',
    '>Periode<' => '>Period<',
    '>Mata Uang<' => '>Currency<',
    '>Material<' => '>Material<',
    '>Harga<' => '>Price<',
    '>Harga/Kg<' => '>Price/Kg<',
    '>Lampiran<' => '>Attachment<',
    '>No. PR<' => '>PR No.<',
    '>No. PO<' => '>PO No.<',
    '>Tambah<' => '>Add<',
    '>Simpan<' => '>Save<',
    '>Batal<' => '>Cancel<',
    '>Hapus<' => '>Delete<',
    '>Edit<' => '>Edit<',
    '>Ubah<' => '>Edit<',
    '>Detail<' => '>Details<',
    '>Kirim<' => '>Send<',
    '>Ajukan<' => '>Submit<',
    '>Konfirmasi<' => '>Confirm<',
    '>Kembali<' => '>Back<',
    '>Tutup<' => '>Close<',
    '>Pilih<' => '>Select<',
    '>Unduh<' => '>Download<',
    '>Cetak<' => '>Print<',
    '>Diterima<' => '>Accepted<',
    '>Ditolak<' => '>Rejected<',
    '>Selesai<' => '>Completed<',
    '>Terkirim<' => '>Submitted<',
    '>Draft<' => '>Draft<',
    '>Kadaluarsa<' => '>Expired<',
    '>Perlu Revisi<' => '>Needs Revision<',
    '>Tuntutan<' => '>Demand<',
    '>Tanggapan<' => '>Response<',
    '>Lampiran Pendukung<' => '>Supporting Attachments<',
    '>Tindakan<' => '>Action<',
    '>Status Klaim<' => '>Claim Status<',
    '>Keputusan<' => '>Decision<',
    '>Masuk<' => '>Login<',
    '>Keluar<' => '>Logout<',
    '>Berhasil<' => '>Success<',
    '>Gagal<' => '>Failed<',
    '>Terima<' => '>Accept<',
    '>Tolak<' => '>Reject<',

    // --- EXACT SENTENCES/PHRASES ---
    'Masa Berlaku Penawaran' => 'Quotation Valid Until',
    'Estimasi Pengiriman/Kedatangan' => 'Estimated Delivery/Arrival',
    'Masa Berlaku' => 'Valid Until',
    'Estimasi Pengiriman' => 'Estimated Delivery',
    'Estimasi Kedatangan' => 'Estimated Arrival',
    'Tgl Diajukan' => 'Date Submitted',
    'Tgl Terkirim' => 'Date Submitted',
    'Tgl Submit' => 'Submit Date',
    'Kata Sandi' => 'Password',
    'Konfirmasi Kata Sandi' => 'Confirm Password',
    'Profil' => 'Profile',
    'Tandai Semua Dibaca' => 'Mark All as Read',
    'Belum ada notifikasi baru' => 'No new notifications',
    'Notifikasi' => 'Notifications',
    'Cari...' => 'Search...',
    'Data tidak ditemukan' => 'Data not found',
    'Belum ada data' => 'No data available',
    'Tidak ada data' => 'No data',
    'Total Permintaan' => 'Total Requirements',
    'Total Penawaran' => 'Total Quotations',
    'Menunggu Persetujuan' => 'Waiting for Approval',
    'Menunggu Review' => 'Waiting for Review',
    'Penawaran Baru' => 'New Quotation',
    'Kembali ke Daftar Permintaan' => 'Back to Requirement List',
    'Kembali ke Daftar Klaim' => 'Back to Claim List',
    'Kembali ke Daftar Inspeksi' => 'Back to Inspection List',
    'Daftar Permintaan Pembelian' => 'Purchase Requirement List',
    'Detail Permintaan Pembelian' => 'Purchase Requirement Details',
    'Detail Permintaan' => 'Requirement Details',
    'Daftar Permintaan' => 'Requirement List',
    'Lihat Permintaan' => 'View Requirement',
    'Daftar Purchase Order yang Diterima' => 'Received Purchase Order List',
    'Menunggu Inspeksi' => 'Waiting for Inspection',
    'Riwayat Inspeksi' => 'Inspection History',
    'Diinspeksi Oleh' => 'Inspected By',
    'Waktu Inspeksi' => 'Inspection Time',
    'Total perubahan (awal → terbaru)' => 'Total change (initial → latest)',
    'Perubahan dari Periode Sebelumnya' => 'Change from Previous Period',
    '% Perubahan' => '% Change',
    'Gagal memuat data historis. Coba pilih filter kembali.' => 'Failed to load historical data. Try selecting filters again.',
    'Gagal memuat data historis' => 'Failed to load historical data',
    'Perlu Respons' => 'Needs Response',
    'Ada Klaim' => 'Has Claim',
    'ADASI mengajukan klaim untuk PO ini. Silakan berikan tanggapan dan lampiran pendukung.' => 'ADASI submitted a claim for this PO. Please provide a response and supporting attachments.',
    'Respons Klaim' => 'Claim Response',
    'PO ini memiliki riwayat klaim material. Buka detail klaim untuk melihat status dan respons.' => 'This PO has a material claim history. Open claim details to view status and response.',
    'aktif yang belum Anda berikan penawaran. Segera ajukan harga terbaik Anda!' => 'active that you have not provided a quotation for. Submit your best price soon!',
    'Permintaan Belum Direspons' => 'Unresponsive Requirements',
    'Semua permintaan sudah direspons!' => 'All requirements have been responded to!',
    'Lihat Klaim' => 'View Claim',
    'Belum ada pengumuman baru.' => 'No new announcements.',
    'Detail Klaim' => 'Claim Details',
    'Klaim #' => 'Claim #',
    'Tuntutan Klaim' => 'Claim Demand',
    'Anda telah merespons klaim ini pada:' => 'You have responded to this claim on:',
    'Kirim Respons Klaim?' => 'Send Claim Response?',
    'Pastikan tanggapan dan resolusi yang Anda tawarkan sudah sesuai. Respons tidak dapat diubah setelah dikirim.' => 'Ensure your response and offered resolution are appropriate. Responses cannot be changed after submission.',
    'Daftar di bawah adalah klaim material NG (Not Good) yang diajukan oleh tim Purchasing ADASI. Harap segera merespons klaim yang berstatus' => 'The list below contains NG (Not Good) material claims submitted by the ADASI Purchasing team. Please immediately respond to claims with status',
    'sebelum batas waktu (deadline).' => 'before the deadline.',
    'ID Klaim' => 'Claim ID',
    'Batas waktu supplier merespons klaim material.' => 'Deadline for supplier to respond to material claims.',
    'Belum ada pengumuman' => 'No announcements yet',
    'Inspeksi PO' => 'PO Inspection',
    'Diinspeksi Oleh' => 'Inspected By',
    'Waktu Inspeksi' => 'Inspection Time',
    'Belum ada foto bukti NG pada inspeksi ini.' => 'No NG evidence photos for this inspection yet.',
    'Cari Status Inspeksi' => 'Search Inspection Status',
    'Tanggal Inspeksi' => 'Inspection Date',
    'Semua material sesuai spesifikasi.' => 'All materials meet specifications.',
    'Terdapat material yang tidak sesuai spesifikasi. Harap unggah foto bukti.' => 'There are materials that do not meet specifications. Please upload evidence photos.',
    'Simpan Hasil Inspeksi' => 'Save Inspection Results',
    'Simpan Hasil Inspeksi?' => 'Save Inspection Results?',
    'Hasil inspeksi tidak dapat diubah setelah disimpan.' => 'Inspection results cannot be changed after saving.',
    'PO status akan diperbarui otomatis.' => 'PO status will be updated automatically.',
    'TOTAL INSPEKSI' => 'TOTAL INSPECTIONS',
    'MENUNGGU INSPEKSI' => 'WAITING FOR INSPECTION',
    'No data available inspeksi.' => 'No inspection data available.',
    '10 Inspeksi Terbaru' => '10 Latest Inspections',
    'Chat tersedia setelah penawaran dikirim supplier atau sudah diterima.' => 'Chat is available after the quotation is submitted by the supplier or accepted.',
    'Total histori memakai kurs snapshot penawaran ini, bukan kurs terbaru.' => 'Historical total uses the exchange rate snapshot of this quotation, not the latest rate.',
    'Terima Quotation' => 'Accept Quotation',
    'Wajib diisi jika penawaran ditolak.' => 'Required if the quotation is rejected.',
    'Tolak Quotation' => 'Reject Quotation',
    'Belum ada penawaran masuk.' => 'No quotations received yet.',
    'Gagal memuat data penawaran.' => 'Failed to load quotation data.',
    'Draft Permintaan' => 'Requirement Draft',
    'Belum ada penawaran masuk dari supplier.' => 'No quotations received from the supplier yet.',
    'Anda melihat permintaan yang dibuat oleh' => 'You are viewing a requirement created by',
    'Aksi edit dan hapus hanya tersedia untuk pembuat PR.' => 'Edit and delete actions are only available to the PR creator.',
    'Permintaan ini masih berstatus draft. Silakan edit dan ajukan jika sudah selesai.' => 'This requirement is still in draft status. Please edit and submit when finished.',
    'Ajukan Permintaan' => 'Submit Requirement',
    'Permintaan ditolak oleh Admin. Silakan periksa catatan dan revisi.' => 'Requirement rejected by Admin. Please check notes and revise.',
    'Permintaan sudah diproses dan tidak dapat diedit lagi.' => 'Requirement has been processed and can no longer be edited.',
    'Ajukan Permintaan?' => 'Submit Requirement?',
    'Status akan berubah menjadi Submitted dan tidak bisa diedit lagi.' => 'Status will change to Submitted and cannot be edited anymore.',
    'Buat Permintaan Baru' => 'Create New Requirement',
    'Permintaan material ini akan dihapus permanen!' => 'This material requirement will be permanently deleted!',
    'PO ini membutuhkan tindak lanjut klaim karena hasil inspeksi QC berstatus NG.' => 'This PO requires claim follow-up because the QC inspection result is NG.',
    'Buka Menu Klaim' => 'Open Claim Menu',
    'Inspeksi berstatus NG, tetapi foto bukti QC belum tersedia.' => 'Inspection status is NG, but QC evidence photos are not yet available.',
    'Quotation revisi akan dikirim ulang ke Purchasing untuk dievaluasi.' => 'Revised quotation will be resent to Purchasing for evaluation.',
    'Quotation yang sudah dikirim tidak dapat diubah lagi.' => 'Submitted quotation cannot be changed anymore.',
    "Anda memiliki perubahan yang belum disimpan. Yakin ingin meninggalkan halaman?" => "You have unsaved changes. Are you sure you want to leave this page?",
    "Simpan Perubahan" => "Save Changes",
    "Quotation supplier lain pada PR yang sama akan otomatis <strong>ditolak</strong>." => "Other suppliers' quotations on the same PR will be automatically <strong>rejected</strong>.",
    "Update kurs terbaru:" => "Latest exchange rate update:",
    "Exchange Rate baru disimpan sebagai histori baru, bukan menimpa kurs lama." => "New Exchange Rate is saved as new history, not overwriting the old one.",
    "Exchange Rate terbaru dipakai untuk input baru. Histori penawaran dan PO tetap memakai kurs snapshot masing-masing." => "Latest Exchange Rate is used for new inputs. Quotation and PO history keep using their respective snapshot rates.",
    "Gagal memperbarui status dokumen." => "Failed to update document status.",
    "Form Pengajuan Klaim" => "Claim Submission Form",
    "Beri waktu wajar untuk supplier merespons klaim ini." => "Give reasonable time for the supplier to respond to this claim.",
    "Kirim Klaim ke Supplier" => "Send Claim to Supplier",
    "Tgl Inspeksi" => "Inspection Date",
    "Aksi Klaim" => "Claim Action",
    "Supplier telah memberikan tanggapan. Apakah solusi bisa diterima?" => "Supplier has provided a response. Is the solution acceptable?",
    "Klaim ini telah dinyatakan selesai dan terselesaikan." => "This claim has been declared completed and resolved.",
    "Daftar PO di bawah ini telah diinspeksi oleh QC dan berstatus NG (Not Good). Silakan ajukan klaim kepada supplier terkait." => "The PO list below has been inspected by QC and has an NG (Not Good) status. Please submit a claim to the relevant supplier.",
    "Pembanding memakai harga IDR/kg setelah konversi kurs. Status kompetitif aman jika selisih maksimal" => "Comparison uses IDR/kg price after exchange rate conversion. Competitive status is safe if maximum difference is",
    "Gagal memuat material" => "Failed to load material",
    "Gagal memuat daftar material. Coba pilih supplier kembali." => "Failed to load material list. Try selecting a supplier again.",
    "Inspeksi Quality Control" => "Quality Control Inspection",
    "Hasil Inspeksi" => "Inspection Result",
    "KESIMPULAN: Ditemukan" => "CONCLUSION: Found",
    "item TIDAK SESUAI SPESIFIKASI (NG). Material memerlukan tindak lanjut klaim." => "items DO NOT MEET SPECIFICATION (NG). Material requires claim follow-up.",
    "Diterima Oleh" => "Received By",
    "Gagal memuat daftar chat." => "Failed to load chat list.",
    "Gagal memuat daftar chat. Coba buka kembali beberapa saat lagi." => "Failed to load chat list. Please try again later.",
    "Terkirim, belum dibaca" => "Sent, unread",
    "Gagal membuka chat." => "Failed to open chat.",
    "Gagal memuat detail chat. Coba buka kembali beberapa saat lagi." => "Failed to load chat details. Please try again later.",
    "PO sedang menunggu inspeksi QC." => "POs are waiting for QC inspection.",
    "PO sedang menunggu" => "POs are waiting",
    "sedang menunggu inspeksi QC." => "are waiting for QC inspection.",
    "sedang menunggu" => "are waiting",

    // --- DATATABLE LANGUAGE REMOVAL ---
    "url: 'https://cdn.datatables.net/plug-ins/1.13.6/i18n/id.json'" => "",
    'url: "https://cdn.datatables.net/plug-ins/1.13.6/i18n/id.json"' => "",
];

$appReplacements = [
    // --- EXACT FLASH / JSON MESSAGES IN CONTROLLERS ---
    "'Berhasil disimpan'" => "'Saved successfully'",
    '"Berhasil disimpan"' => '"Saved successfully"',
    "'Berhasil ditambahkan'" => "'Added successfully'",
    '"Berhasil ditambahkan"' => '"Added successfully"',
    "'Berhasil diubah'" => "'Updated successfully'",
    '"Berhasil diubah"' => '"Updated successfully"',
    "'Berhasil dihapus'" => "'Deleted successfully'",
    '"Berhasil dihapus"' => '"Deleted successfully"',
    "'Berhasil dikirim'" => "'Sent successfully'",
    '"Berhasil dikirim"' => '"Sent successfully"',
    "'Gagal disimpan'" => "'Failed to save'",
    '"Gagal disimpan"' => '"Failed to save"',
    "'Gagal dihapus'" => "'Failed to delete'",
    '"Gagal dihapus"' => '"Failed to delete"',
    "'Permintaan material berhasil diajukan.'" => "'Purchase Requirement successfully submitted.'",
    "'Penawaran berhasil dikirim.'" => "'Quotation successfully sent.'",

    // --- STATUS LABELS MAPPED DYNAMICALLY ---
    "'Diterima'" => "'Accepted'",
    '"Diterima"' => '"Accepted"',
    "'Ditolak'" => "'Rejected'",
    '"Ditolak"' => '"Rejected"',
    "'Terkirim'" => "'Submitted'",
    '"Terkirim"' => '"Submitted"',
    "'Selesai'" => "'Completed'",
    '"Selesai"' => '"Completed"',
    "'Kadaluarsa'" => "'Expired'",
    '"Kadaluarsa"' => '"Expired"',
    "'Perlu Revisi'" => "'Needs Revision'",
    '"Perlu Revisi"' => '"Needs Revision"',
    "'Draft'" => "'Draft'",
    '"Draft"' => '"Draft"',
    "'Belum Ada'" => "'Not Available'",
    "'Sudah Diterbitkan'" => "'Issued'",
    "'Diverifikasi'" => "'Verified'",
];

function processDirectory($dir, $replacements) {
    $iterator = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($dir));
    $count = 0;
    foreach ($iterator as $file) {
        if ($file->isFile() && in_array($file->getExtension(), ['php'])) {
            $content = file_get_contents($file->getPathname());
            $newContent = strtr($content, $replacements);
            
            // Extra safe regex for attributes
            $newContent = preg_replace('/placeholder=["\']([^"\']*?)Cari\.\.\.([^"\']*?)["\']/i', 'placeholder="Search..."', $newContent);
            $newContent = preg_replace('/title=["\']([^"\']*?)Hapus([^"\']*?)["\']/i', 'title="Delete"', $newContent);
            $newContent = preg_replace('/title=["\']([^"\']*?)Edit([^"\']*?)["\']/i', 'title="Edit"', $newContent);
            $newContent = preg_replace('/title=["\']([^"\']*?)Detail([^"\']*?)["\']/i', 'title="Details"', $newContent);
            
            // Datatables cleanup
            $newContent = preg_replace('/language:\s*{\s*,\s*}/m', '', $newContent);
            $newContent = preg_replace('/language:\s*{\s*}/m', '', $newContent);

            if ($content !== $newContent) {
                file_put_contents($file->getPathname(), $newContent);
                $count++;
            }
        }
    }
    return $count;
}

echo "Starting SAFE translation bulk script...\n";
$viewsChanged = processDirectory($viewsDir, $replacements);
echo "Views changed: $viewsChanged files.\n";

$appChanged = processDirectory($appDir, $appReplacements);
echo "App (Controllers/Exports/Models) changed: $appChanged files.\n";

echo "Done.\n";
