@extends('layouts.app')
@section('title', __('finance.voucher.title').': '.$voucher->voucher_number.' - ADASI Portal')
@section('page-title', __('finance.voucher.title'))
@section('content')
<div class="tw-grid tw-max-w-6xl tw-gap-6 tw-pb-16"><x-ui.page-header :title="$voucher->voucher_number" :description="$voucher->supplier_name_snapshot.' · '.$voucher->invoice_number_snapshot" :eyebrow="__('finance.voucher.final')"><x-slot:actions><x-ui.button :href="route('finance.vouchers.print',$voucher)" variant="outline" size="sm" target="_blank"><x-ui.icon name="printer" size="sm" /> {{ __('finance.voucher.print_pdf') }}</x-ui.button><x-ui.button :href="route('finance.drp.show',$voucher->batch)" variant="ghost" size="sm">{{ __('finance.voucher.back_drp') }}</x-ui.button></x-slot:actions></x-ui.page-header>
<div class="tw-grid tw-gap-6 lg:tw-grid-cols-2"><x-ui.card :title="__('finance.voucher.snapshot')"><dl class="tw-grid tw-grid-cols-2 tw-gap-3 tw-text-ui-sm"><dt>{{ __('finance.voucher.date') }}</dt><dd>{{ $regionalFormatter->date($voucher->voucher_date, 'human') }}</dd><dt>Invoice</dt><dd>{{ $voucher->invoice_number_snapshot }}</dd><dt>PO</dt><dd>{{ $voucher->po_number_snapshot }}</dd><dt>GR</dt><dd>{{ $voucher->gr_references_snapshot }}</dd><dt>{{ __('finance.voucher.payment_method') }}</dt><dd>{{ $voucher->payment_method === 'KAS' ? __('finance.voucher.cash') : $voucher->payment_method }}</dd><dt>{{ __('common.labels_review.bank') }}</dt><dd>{{ $voucher->bank_name_snapshot }} · {{ $voucher->bank_account_snapshot }}</dd><dt>DPP</dt><dd class="tw-font-mono">Rp {{ number_format($voucher->dpp_snapshot,2,',','.') }}</dd><dt>PPN</dt><dd class="tw-font-mono">Rp {{ number_format($voucher->ppn_snapshot,2,',','.') }}</dd><dt>{{ __('finance.voucher.withholding_label') }}</dt><dd class="tw-font-mono">Rp {{ number_format($voucher->pph_snapshot,2,',','.') }}</dd><dt>{{ __('finance.voucher.total_amount') }}</dt><dd class="tw-font-mono tw-font-bold">Rp {{ number_format($voucher->amount,2,',','.') }}</dd></dl></x-ui.card>
<x-ui.card :title="__('finance.voucher.settlement_title')" :description="__('finance.voucher.settlement_help')">@if(!$voucher->payment)
<div class="tw-rounded-xl tw-border tw-border-primary/20 tw-bg-primary/5 tw-p-5">
    <div class="tw-flex tw-items-start tw-gap-3">
        <div class="tw-flex-shrink-0 tw-mt-0.5"><x-ui.icon name="info" size="sm" class="tw-text-primary" /></div>
        <div class="tw-flex-1">
            <h4 class="tw-text-ui-sm tw-font-bold tw-text-on-surface tw-m-0 tw-mb-1">{{ __('finance.voucher.awaiting_payment') }}</h4>
            <p class="tw-text-ui-xs tw-text-on-surface-variant tw-m-0 tw-mb-3">{{ __('finance.voucher.awaiting_help', ['menu' => __('navigation.drp_paid')]) }}</p>
            <x-ui.button :href="route('finance.drp.paid.index', ['q' => $voucher->batch?->batch_number])" size="sm" variant="primary">
                <x-ui.icon name="external-link" size="sm" /> {{ __('finance.drp.open_paid_menu') }}
            </x-ui.button>
        </div>
    </div>
</div>
@else
<div class="tw-mb-4"><x-ui.status-chip :tone="\App\Support\StatusHelper::localFinanceTone($voucher->payment->status)">{{ \App\Support\StatusHelper::localFinanceLabel($voucher->payment->status) }}</x-ui.status-chip><div class="tw-mt-2 tw-text-ui-sm">{{ __('finance.voucher.target_actual', ['expected' => number_format($voucher->payment->expected_amount,2,',','.'), 'actual' => number_format($voucher->payment->actual_paid_total,2,',','.')]) }}</div>@if($voucher->payment->transfers->isNotEmpty())<div class="tw-mt-1 tw-text-ui-xs tw-text-on-surface-variant">{{ __('finance.voucher.transfer_details', ['reference' => $voucher->payment->transfers->first()->transfer_reference, 'date' => $regionalFormatter->date($voucher->payment->transfers->first()->transfer_date, 'human') ?? '?']) }}</div>@endif</div><ol class="tw-space-y-2">@foreach($voucher->payment->transfers as $transfer)<li class="tw-rounded-lg tw-bg-surface-container tw-p-3 tw-text-ui-sm"><strong>{{ match($transfer->transfer_type) { 'PRIMARY' => __('local_invoice.labels.primary_transfer'), 'CORRECTION' => __('local_invoice.labels.correction_transfer'), default => $transfer->transfer_type } }} #{{ $transfer->sequence_no }}</strong> · {{ $transfer->transfer_reference }} · {{ $regionalFormatter->date($transfer->transfer_date, 'human') ?? '?' }} · Rp {{ number_format($transfer->amount,2,',','.')}}@if($transfer->correction_reason)<div>{{ $transfer->correction_reason }}</div>@endif</li>@endforeach</ol>
@if($voucher->payment->status==='CORRECTION_REQUIRED')<form method="POST" action="{{ route('finance.settlements.correction',$voucher->payment) }}" class="tw-mt-4 tw-grid tw-gap-3">@csrf<input name="amount" type="number" step="0.01" min="0.01" class="form-control" placeholder="{{ __('finance.voucher.correction_amount') }}" required><input name="transfer_reference" class="form-control" placeholder="{{ __('local_invoice.labels.bank_reference') }}" required><x-ui.date-picker id="voucher_correction_transfer_date" name="transfer_date" :value="now()->format('Y-m-d')" required /><textarea name="correction_reason" class="form-control" placeholder="{{ __('finance.payment.correction_reason') }}" required></textarea><x-ui.button type="submit">{{ __('finance.payment.save_correction') }}</x-ui.button></form>@endif @endif</x-ui.card></div></div>
@endsection
