<?php

use App\Notifications\SystemNotification;

return [
    'pr_submitted' => [
        'class' => SystemNotification::class,
        'source_event' => 'pr.submitted',
        'label' => 'Purchase requisition submitted',
        'description' => 'A purchase requisition is submitted for review.',
        'category' => 'Purchase requisitions',
        'roles' => ['admin'],
        'supplier_scopes' => [],
        'default' => true,
    ],
    'quotation_submitted' => [
        'class' => SystemNotification::class,
        'source_event' => 'quotation.submitted',
        'label' => 'Quotation submitted',
        'description' => 'A supplier submits a quotation.',
        'category' => 'Quotations',
        'roles' => ['purchasing'],
        'supplier_scopes' => [],
        'default' => true,
        'priority' => 'action_required',
    ],
    'quotation_revised' => [
        'class' => SystemNotification::class,
        'source_event' => 'quotation.revised',
        'label' => 'Revised quotation submitted',
        'description' => 'A supplier resubmits a revised quotation.',
        'category' => 'Quotations',
        'roles' => ['purchasing'],
        'supplier_scopes' => [],
        'default' => true,
        'priority' => 'action_required',
    ],
    'quotation_accepted' => [
        'class' => SystemNotification::class,
        'source_event' => 'quotation.accepted',
        'label' => 'Quotation accepted',
        'description' => 'Purchasing accepts your quotation.',
        'category' => 'Quotations',
        'roles' => ['supplier'],
        'supplier_scopes' => ['import'],
        'default' => true,
    ],
    'quotation_rejected' => [
        'class' => SystemNotification::class,
        'source_event' => 'quotation.rejected',
        'label' => 'Quotation rejected',
        'description' => 'Purchasing rejects your quotation.',
        'category' => 'Quotations',
        'roles' => ['supplier'],
        'supplier_scopes' => ['import'],
        'default' => true,
    ],
    'quotation_revision_requested' => [
        'class' => SystemNotification::class,
        'source_event' => 'quotation.revision_requested',
        'label' => 'Quotation revision requested',
        'description' => 'Purchasing asks you to revise a quotation.',
        'category' => 'Quotations',
        'roles' => ['supplier'],
        'supplier_scopes' => ['import'],
        'default' => true,
        'priority' => 'action_required',
    ],
    'quotation_negotiation_message' => [
        'class' => SystemNotification::class,
        'source_event' => 'quotation.negotiation_message',
        'label' => 'Negotiation request',
        'description' => 'Purchasing sends a negotiation request about your quotation.',
        'category' => 'Conversations',
        'roles' => ['supplier'],
        'supplier_scopes' => ['import'],
        'default' => true,
        'priority' => 'action_required',
    ],
    'conversation_message_created' => [
        'class' => SystemNotification::class,
        'source_event' => 'conversation.message_created',
        'label' => 'Conversation message',
        'description' => 'Your conversation partner sends a message or attachment.',
        'category' => 'Conversations',
        'roles' => ['purchasing', 'supplier'],
        'supplier_scopes' => ['import'],
        'default' => true,
    ],
    'po_issued' => [
        'class' => SystemNotification::class,
        'source_event' => 'po.issued',
        'label' => 'Purchase order issued',
        'description' => 'A purchase order is issued for your awarded items.',
        'category' => 'Purchase orders',
        'roles' => ['supplier'],
        'supplier_scopes' => ['import'],
        'default' => true,
        'priority' => 'action_required',
    ],
    'document_status_updated' => [
        'class' => SystemNotification::class,
        'source_event' => 'document.status_updated',
        'label' => 'Import document status updated',
        'description' => 'An import document status changes on a purchase order you created.',
        'category' => 'Documents',
        'roles' => ['admin', 'purchasing', 'qc', 'supplier'],
        'supplier_scopes' => ['import'],
        'default' => true,
        'eligibility' => 'import_po_creator',
    ],
    'document_all_completed' => [
        'class' => SystemNotification::class,
        'source_event' => 'document.all_completed',
        'label' => 'Import documents complete',
        'description' => 'All required import documents are complete for a purchase order you created.',
        'category' => 'Documents',
        'roles' => ['admin', 'purchasing', 'qc', 'supplier'],
        'supplier_scopes' => ['import'],
        'default' => true,
        'eligibility' => 'import_po_creator',
    ],
    'po_item_progress_updated' => [
        'class' => SystemNotification::class,
        'source_event' => 'po_item_progress.updated',
        'label' => 'Material progress updated',
        'description' => 'A supplier updates material progress or estimated readiness.',
        'category' => 'Purchase orders',
        'roles' => ['purchasing'],
        'supplier_scopes' => [],
        'default' => true,
    ],
    'shipment_submitted' => [
        'class' => SystemNotification::class,
        'source_event' => 'shipment.submitted',
        'label' => 'Shipment submitted',
        'description' => 'A supplier submits a shipment.',
        'category' => 'Shipments and QC',
        'roles' => ['purchasing'],
        'supplier_scopes' => [],
        'default' => true,
        'priority' => 'action_required',
    ],
    'po_material_arrived' => [
        'class' => SystemNotification::class,
        'source_event' => 'po.material_arrived',
        'label' => 'Material ready for QC',
        'description' => 'Material arrives and is ready for quality inspection.',
        'category' => 'Shipments and QC',
        'roles' => ['qc'],
        'supplier_scopes' => [],
        'default' => true,
        'priority' => 'action_required',
    ],
    'qc_inspection_ok' => [
        'class' => SystemNotification::class,
        'source_event' => 'qc.inspection_ok',
        'label' => 'QC inspection passed',
        'description' => 'Material passes quality inspection.',
        'category' => 'Shipments and QC',
        'roles' => ['purchasing'],
        'supplier_scopes' => [],
        'default' => true,
    ],
    'qc_inspection_ng' => [
        'class' => SystemNotification::class,
        'source_event' => 'qc.inspection_ng',
        'label' => 'QC inspection failed',
        'description' => 'Quality inspection identifies material that requires a claim.',
        'category' => 'Shipments and QC',
        'roles' => ['purchasing'],
        'supplier_scopes' => [],
        'default' => true,
    ],
    'claim_created' => [
        'class' => SystemNotification::class,
        'source_event' => 'claim.created',
        'label' => 'Material claim created',
        'description' => 'Purchasing creates a claim for your material.',
        'category' => 'Material claims',
        'roles' => ['supplier'],
        'supplier_scopes' => ['import'],
        'default' => true,
        'priority' => 'action_required',
    ],
    'claim_responded' => [
        'class' => SystemNotification::class,
        'source_event' => 'claim.responded',
        'label' => 'Material claim response',
        'description' => 'A supplier responds to a material claim.',
        'category' => 'Material claims',
        'roles' => ['purchasing'],
        'supplier_scopes' => [],
        'default' => true,
    ],
    'claim_resolved' => [
        'class' => SystemNotification::class,
        'source_event' => 'claim.resolved',
        'label' => 'Material claim resolved',
        'description' => 'Purchasing completes your material claim.',
        'category' => 'Material claims',
        'roles' => ['supplier'],
        'supplier_scopes' => ['import'],
        'default' => true,
    ],
    'local_invoice_submitted' => [
        'class' => SystemNotification::class,
        'source_event' => 'local_invoice.submitted',
        'label' => 'Invoice diajukan',
        'description' => 'Pengajuan invoice baru diterima oleh sistem.',
        'category' => 'Local invoices',
        'roles' => ['finance', 'accounting', 'supplier'],
        'supplier_scopes' => ['local'],
        'default' => true,
        'priority' => 'action_required',
        'priority_roles' => ['finance', 'accounting'],
    ],
    'local_invoice_resubmitted' => [
        'class' => SystemNotification::class,
        'source_event' => 'local_invoice.resubmitted',
        'label' => 'Invoice diajukan ulang',
        'description' => 'Revisi invoice diajukan ulang untuk verifikasi.',
        'category' => 'Local invoices',
        'roles' => ['finance', 'accounting', 'supplier'],
        'supplier_scopes' => ['local'],
        'default' => true,
        'priority' => 'action_required',
        'priority_roles' => ['finance', 'accounting'],
    ],
    'local_invoice_cancelled' => [
        'class' => SystemNotification::class,
        'source_event' => 'local_invoice.cancelled',
        'label' => 'Invoice dibatalkan',
        'description' => 'Pengajuan invoice Anda dibatalkan.',
        'category' => 'Local invoices',
        'roles' => ['supplier'],
        'supplier_scopes' => ['local'],
        'default' => true,
    ],
    'local_invoice_physical_received' => [
        'class' => SystemNotification::class,
        'source_event' => 'local_invoice.physical_received',
        'label' => 'Berkas fisik diterima',
        'description' => 'Kasir mencatat penerimaan berkas fisik invoice Anda.',
        'category' => 'Local invoices',
        'roles' => ['supplier'],
        'supplier_scopes' => ['local'],
        'default' => true,
    ],
    'local_invoice_approved' => [
        'class' => SystemNotification::class,
        'source_event' => 'local_invoice.approved',
        'label' => 'Invoice siap dibayar',
        'description' => 'Invoice Anda disetujui dan masuk status Ready to Pay.',
        'category' => 'Local invoices',
        'roles' => ['supplier'],
        'supplier_scopes' => ['local'],
        'default' => true,
    ],
    'local_invoice_revision_requested' => [
        'class' => SystemNotification::class,
        'source_event' => 'local_invoice.revision_requested',
        'label' => 'Revisi invoice diminta',
        'description' => 'Finance meminta revisi invoice Anda.',
        'category' => 'Local invoices',
        'roles' => ['supplier'],
        'supplier_scopes' => ['local'],
        'default' => true,
        'priority' => 'action_required',
    ],
    'local_invoice_rejected' => [
        'class' => SystemNotification::class,
        'source_event' => 'local_invoice.rejected',
        'label' => 'Invoice ditolak',
        'description' => 'Finance menolak pengajuan invoice Anda.',
        'category' => 'Local invoices',
        'roles' => ['supplier'],
        'supplier_scopes' => ['local'],
        'default' => true,
    ],
    'local_invoice_partial_payment' => [
        'class' => SystemNotification::class,
        'source_event' => 'local_invoice.partial_payment',
        'label' => 'Koreksi pembayaran diperlukan',
        'description' => 'Transfer aktual belum memenuhi nilai settlement invoice Anda.',
        'category' => 'Local invoices',
        'roles' => ['supplier'],
        'supplier_scopes' => ['local'],
        'default' => true,
        'priority' => 'action_required',
    ],
    'local_invoice_paid' => [
        'class' => SystemNotification::class,
        'source_event' => 'local_invoice.paid',
        'label' => 'Invoice dibayar',
        'description' => 'Settlement pembayaran invoice Anda selesai.',
        'category' => 'Local invoices',
        'roles' => ['supplier'],
        'supplier_scopes' => ['local'],
        'default' => true,
    ],
    'local_invoice_overpaid' => [
        'class' => SystemNotification::class,
        'source_event' => 'local_invoice.overpaid',
        'label' => 'Kelebihan bayar tercatat',
        'description' => 'Kelebihan pembayaran invoice Anda dicatat sebagai pengembalian dana.',
        'category' => 'Local invoices',
        'roles' => ['supplier'],
        'supplier_scopes' => ['local'],
        'default' => true,
    ],
    'local_invoice_refund_settled' => [
        'class' => SystemNotification::class,
        'source_event' => 'local_invoice.refund_settled',
        'label' => 'Pengembalian dana selesai',
        'description' => 'Pengembalian kelebihan pembayaran Anda dicatat selesai.',
        'category' => 'Local invoices',
        'roles' => ['supplier'],
        'supplier_scopes' => ['local'],
        'default' => true,
    ],
    'local_invoice_physical_delivery_reminder' => [
        'class' => SystemNotification::class,
        'source_event' => 'local_invoice.physical_delivery_reminder',
        'label' => 'Pengingat pengiriman berkas',
        'description' => 'Jadwal penyerahan berkas fisik invoice Anda sudah dekat.',
        'category' => 'Local invoices',
        'roles' => ['supplier'],
        'supplier_scopes' => ['local'],
        'default' => true,
        'priority' => 'action_required',
    ],
    'supplier_registration_submitted' => [
        'class' => SystemNotification::class,
        'source_event' => 'supplier_registration.submitted',
        'label' => 'Supplier registration submitted',
        'description' => 'A supplier submits a new registration.',
        'category' => 'Supplier registration',
        'roles' => ['admin', 'finance', 'purchasing'],
        'supplier_scopes' => [],
        'default' => true,
        'priority' => 'action_required',
    ],
    'supplier_registration_resubmitted' => [
        'class' => SystemNotification::class,
        'source_event' => 'supplier_registration.resubmitted',
        'label' => 'Supplier registration resubmitted',
        'description' => 'A supplier resubmits a revised registration.',
        'category' => 'Supplier registration',
        'roles' => ['admin', 'finance', 'purchasing'],
        'supplier_scopes' => [],
        'default' => true,
        'priority' => 'action_required',
    ],
    'supplier_registration_revision_requested' => [
        'class' => SystemNotification::class,
        'source_event' => 'supplier_registration.revision_requested',
        'label' => 'Registration revision requested',
        'description' => 'A reviewer requests changes to a supplier registration.',
        'category' => 'Supplier registration',
        'roles' => ['admin', 'finance', 'purchasing'],
        'supplier_scopes' => [],
        'default' => true,
    ],
    'supplier_registration_rejected' => [
        'class' => SystemNotification::class,
        'source_event' => 'supplier_registration.rejected',
        'label' => 'Supplier registration rejected',
        'description' => 'A reviewer rejects a supplier registration.',
        'category' => 'Supplier registration',
        'roles' => ['admin', 'finance', 'purchasing'],
        'supplier_scopes' => [],
        'default' => true,
    ],
    'supplier_registration_approved' => [
        'class' => SystemNotification::class,
        'source_event' => 'supplier_registration.approved',
        'label' => 'Supplier registration approved',
        'description' => 'A reviewer approves a supplier registration.',
        'category' => 'Supplier registration',
        'roles' => ['admin', 'finance', 'purchasing'],
        'supplier_scopes' => [],
        'default' => true,
    ],
    'export_completed' => [
        'class' => SystemNotification::class,
        'source_event' => 'export.completed',
        'label' => 'Export completed',
        'description' => 'Your export is ready to download.',
        'category' => 'Exports',
        'roles' => ['admin', 'purchasing', 'qc', 'finance', 'accounting', 'ga', 'supplier'],
        'supplier_scopes' => [],
        'default' => true,
        'eligibility' => 'export_owner',
    ],
    'export_failed' => [
        'class' => SystemNotification::class,
        'source_event' => 'export.failed',
        'label' => 'Export failed',
        'description' => 'Your export could not be completed.',
        'category' => 'Exports',
        'roles' => ['admin', 'purchasing', 'qc', 'finance', 'accounting', 'ga', 'supplier'],
        'supplier_scopes' => [],
        'default' => true,
        'eligibility' => 'export_owner',
    ],
    'new_device_login' => [
        'class' => SystemNotification::class,
        'source_event' => 'new_device_login',
        'label' => 'New device sign-in',
        'description' => 'Your account is signed in on a new device.',
        'category' => 'Security',
        'roles' => ['admin', 'purchasing', 'supplier', 'qc', 'accounting', 'finance', 'ga'],
        'supplier_scopes' => [],
        'default' => true,
        'priority' => 'action_required',
    ],
    'repeated_lockouts_detected' => [
        'class' => SystemNotification::class,
        'source_event' => 'repeated_lockouts_detected',
        'label' => 'Repeated sign-in lockouts',
        'description' => 'An account reaches the repeated sign-in lockout threshold.',
        'category' => 'Security',
        'roles' => ['admin'],
        'supplier_scopes' => [],
        'default' => true,
        'priority' => 'action_required',
    ],
];
