<?php

use App\Notifications\SystemNotification;

return [
    'pr_submitted' => [
        'class' => SystemNotification::class,
        'source_event' => 'pr.submitted',
        'label' => 'notifications.events.pr_submitted.label',
        'description' => 'notifications.events.pr_submitted.description',
        'category' => 'notifications.categories.requisitions',
        'roles' => ['admin'],
        'supplier_scopes' => [],
        'default' => true,
    ],
    'quotation_submitted' => [
        'class' => SystemNotification::class,
        'source_event' => 'quotation.submitted',
        'label' => 'notifications.events.quotation_submitted.label',
        'description' => 'notifications.events.quotation_submitted.description',
        'category' => 'notifications.categories.quotations',
        'roles' => ['purchasing'],
        'supplier_scopes' => [],
        'default' => true,
        'priority' => 'action_required',
    ],
    'quotation_revised' => [
        'class' => SystemNotification::class,
        'source_event' => 'quotation.revised',
        'label' => 'notifications.events.quotation_revised.label',
        'description' => 'notifications.events.quotation_revised.description',
        'category' => 'notifications.categories.quotations',
        'roles' => ['purchasing'],
        'supplier_scopes' => [],
        'default' => true,
        'priority' => 'action_required',
    ],
    'quotation_accepted' => [
        'class' => SystemNotification::class,
        'source_event' => 'quotation.accepted',
        'label' => 'notifications.events.quotation_accepted.label',
        'description' => 'notifications.events.quotation_accepted.description',
        'category' => 'notifications.categories.quotations',
        'roles' => ['supplier'],
        'supplier_scopes' => ['import'],
        'default' => true,
    ],
    'quotation_rejected' => [
        'class' => SystemNotification::class,
        'source_event' => 'quotation.rejected',
        'label' => 'notifications.events.quotation_rejected.label',
        'description' => 'notifications.events.quotation_rejected.description',
        'category' => 'notifications.categories.quotations',
        'roles' => ['supplier'],
        'supplier_scopes' => ['import'],
        'default' => true,
    ],
    'quotation_revision_requested' => [
        'class' => SystemNotification::class,
        'source_event' => 'quotation.revision_requested',
        'label' => 'notifications.events.quotation_revision_requested.label',
        'description' => 'notifications.events.quotation_revision_requested.description',
        'category' => 'notifications.categories.quotations',
        'roles' => ['supplier'],
        'supplier_scopes' => ['import'],
        'default' => true,
        'priority' => 'action_required',
    ],
    'quotation_negotiation_message' => [
        'class' => SystemNotification::class,
        'source_event' => 'quotation.negotiation_message',
        'label' => 'notifications.events.quotation_negotiation_message.label',
        'description' => 'notifications.events.quotation_negotiation_message.description',
        'category' => 'notifications.categories.conversations',
        'roles' => ['supplier'],
        'supplier_scopes' => ['import'],
        'default' => true,
        'priority' => 'action_required',
    ],
    'conversation_message_created' => [
        'class' => SystemNotification::class,
        'source_event' => 'conversation.message_created',
        'label' => 'notifications.events.conversation_message_created.label',
        'description' => 'notifications.events.conversation_message_created.description',
        'category' => 'notifications.categories.conversations',
        'roles' => ['purchasing', 'supplier'],
        'supplier_scopes' => ['import'],
        'default' => true,
        'mutable_subject' => 'conversation',
    ],
    'po_issued' => [
        'class' => SystemNotification::class,
        'source_event' => 'po.issued',
        'label' => 'notifications.events.po_issued.label',
        'description' => 'notifications.events.po_issued.description',
        'category' => 'notifications.categories.purchase_orders',
        'roles' => ['supplier'],
        'supplier_scopes' => ['import'],
        'default' => true,
        'priority' => 'action_required',
    ],
    'document_status_updated' => [
        'class' => SystemNotification::class,
        'source_event' => 'document.status_updated',
        'label' => 'notifications.events.document_status_updated.label',
        'description' => 'notifications.events.document_status_updated.description',
        'category' => 'notifications.categories.documents',
        'roles' => ['admin', 'purchasing', 'qc', 'supplier'],
        'supplier_scopes' => ['import'],
        'default' => true,
        'eligibility' => 'import_po_creator',
    ],
    'document_all_completed' => [
        'class' => SystemNotification::class,
        'source_event' => 'document.all_completed',
        'label' => 'notifications.events.document_all_completed.label',
        'description' => 'notifications.events.document_all_completed.description',
        'category' => 'notifications.categories.documents',
        'roles' => ['admin', 'purchasing', 'qc', 'supplier'],
        'supplier_scopes' => ['import'],
        'default' => true,
        'eligibility' => 'import_po_creator',
    ],
    'po_item_progress_updated' => [
        'class' => SystemNotification::class,
        'source_event' => 'po_item_progress.updated',
        'label' => 'notifications.events.po_item_progress_updated.label',
        'description' => 'notifications.events.po_item_progress_updated.description',
        'category' => 'notifications.categories.purchase_orders',
        'roles' => ['purchasing'],
        'supplier_scopes' => [],
        'default' => true,
    ],
    'shipment_submitted' => [
        'class' => SystemNotification::class,
        'source_event' => 'shipment.submitted',
        'label' => 'notifications.events.shipment_submitted.label',
        'description' => 'notifications.events.shipment_submitted.description',
        'category' => 'notifications.categories.shipments_qc',
        'roles' => ['purchasing'],
        'supplier_scopes' => [],
        'default' => true,
        'priority' => 'action_required',
    ],
    'po_material_arrived' => [
        'class' => SystemNotification::class,
        'source_event' => 'po.material_arrived',
        'label' => 'notifications.events.po_material_arrived.label',
        'description' => 'notifications.events.po_material_arrived.description',
        'category' => 'notifications.categories.shipments_qc',
        'roles' => ['qc'],
        'supplier_scopes' => [],
        'default' => true,
        'priority' => 'action_required',
    ],
    'qc_inspection_ok' => [
        'class' => SystemNotification::class,
        'source_event' => 'qc.inspection_ok',
        'label' => 'notifications.events.qc_inspection_ok.label',
        'description' => 'notifications.events.qc_inspection_ok.description',
        'category' => 'notifications.categories.shipments_qc',
        'roles' => ['purchasing'],
        'supplier_scopes' => [],
        'default' => true,
    ],
    'qc_inspection_ng' => [
        'class' => SystemNotification::class,
        'source_event' => 'qc.inspection_ng',
        'label' => 'notifications.events.qc_inspection_ng.label',
        'description' => 'notifications.events.qc_inspection_ng.description',
        'category' => 'notifications.categories.shipments_qc',
        'roles' => ['purchasing'],
        'supplier_scopes' => [],
        'default' => true,
    ],
    'claim_created' => [
        'class' => SystemNotification::class,
        'source_event' => 'claim.created',
        'label' => 'notifications.events.claim_created.label',
        'description' => 'notifications.events.claim_created.description',
        'category' => 'notifications.categories.claims',
        'roles' => ['supplier'],
        'supplier_scopes' => ['import'],
        'default' => true,
        'priority' => 'action_required',
    ],
    'claim_responded' => [
        'class' => SystemNotification::class,
        'source_event' => 'claim.responded',
        'label' => 'notifications.events.claim_responded.label',
        'description' => 'notifications.events.claim_responded.description',
        'category' => 'notifications.categories.claims',
        'roles' => ['purchasing'],
        'supplier_scopes' => [],
        'default' => true,
    ],
    'claim_resolved' => [
        'class' => SystemNotification::class,
        'source_event' => 'claim.resolved',
        'label' => 'notifications.events.claim_resolved.label',
        'description' => 'notifications.events.claim_resolved.description',
        'category' => 'notifications.categories.claims',
        'roles' => ['supplier'],
        'supplier_scopes' => ['import'],
        'default' => true,
    ],
    'local_invoice_submitted' => [
        'class' => SystemNotification::class,
        'source_event' => 'local_invoice.submitted',
        'label' => 'notifications.events.local_invoice_submitted.label',
        'description' => 'notifications.events.local_invoice_submitted.description',
        'category' => 'notifications.categories.local_invoices',
        'roles' => ['finance', 'accounting', 'supplier'],
        'supplier_scopes' => ['local'],
        'default' => true,
        'priority' => 'action_required',
        'priority_roles' => ['finance', 'accounting'],
    ],
    'local_invoice_resubmitted' => [
        'class' => SystemNotification::class,
        'source_event' => 'local_invoice.resubmitted',
        'label' => 'notifications.events.local_invoice_resubmitted.label',
        'description' => 'notifications.events.local_invoice_resubmitted.description',
        'category' => 'notifications.categories.local_invoices',
        'roles' => ['finance', 'accounting', 'supplier'],
        'supplier_scopes' => ['local'],
        'default' => true,
        'priority' => 'action_required',
        'priority_roles' => ['finance', 'accounting'],
    ],
    'local_invoice_cancelled' => [
        'class' => SystemNotification::class,
        'source_event' => 'local_invoice.cancelled',
        'label' => 'notifications.events.local_invoice_cancelled.label',
        'description' => 'notifications.events.local_invoice_cancelled.description',
        'category' => 'notifications.categories.local_invoices',
        'roles' => ['supplier'],
        'supplier_scopes' => ['local'],
        'default' => true,
    ],
    'local_invoice_physical_received' => [
        'class' => SystemNotification::class,
        'source_event' => 'local_invoice.physical_received',
        'label' => 'notifications.events.local_invoice_physical_received.label',
        'description' => 'notifications.events.local_invoice_physical_received.description',
        'category' => 'notifications.categories.local_invoices',
        'roles' => ['supplier'],
        'supplier_scopes' => ['local'],
        'default' => true,
    ],
    'local_invoice_approved' => [
        'class' => SystemNotification::class,
        'source_event' => 'local_invoice.approved',
        'label' => 'notifications.events.local_invoice_approved.label',
        'description' => 'notifications.events.local_invoice_approved.description',
        'category' => 'notifications.categories.local_invoices',
        'roles' => ['supplier'],
        'supplier_scopes' => ['local'],
        'default' => true,
    ],
    'local_invoice_revision_requested' => [
        'class' => SystemNotification::class,
        'source_event' => 'local_invoice.revision_requested',
        'label' => 'notifications.events.local_invoice_revision_requested.label',
        'description' => 'notifications.events.local_invoice_revision_requested.description',
        'category' => 'notifications.categories.local_invoices',
        'roles' => ['supplier'],
        'supplier_scopes' => ['local'],
        'default' => true,
        'priority' => 'action_required',
    ],
    'local_invoice_rejected' => [
        'class' => SystemNotification::class,
        'source_event' => 'local_invoice.rejected',
        'label' => 'notifications.events.local_invoice_rejected.label',
        'description' => 'notifications.events.local_invoice_rejected.description',
        'category' => 'notifications.categories.local_invoices',
        'roles' => ['supplier'],
        'supplier_scopes' => ['local'],
        'default' => true,
    ],
    'local_invoice_partial_payment' => [
        'class' => SystemNotification::class,
        'source_event' => 'local_invoice.partial_payment',
        'label' => 'notifications.events.local_invoice_partial_payment.label',
        'description' => 'notifications.events.local_invoice_partial_payment.description',
        'category' => 'notifications.categories.local_invoices',
        'roles' => ['supplier'],
        'supplier_scopes' => ['local'],
        'default' => true,
        'priority' => 'action_required',
    ],
    'local_invoice_paid' => [
        'class' => SystemNotification::class,
        'source_event' => 'local_invoice.paid',
        'label' => 'notifications.events.local_invoice_paid.label',
        'description' => 'notifications.events.local_invoice_paid.description',
        'category' => 'notifications.categories.local_invoices',
        'roles' => ['supplier'],
        'supplier_scopes' => ['local'],
        'default' => true,
    ],
    'local_invoice_overpaid' => [
        'class' => SystemNotification::class,
        'source_event' => 'local_invoice.overpaid',
        'label' => 'notifications.events.local_invoice_overpaid.label',
        'description' => 'notifications.events.local_invoice_overpaid.description',
        'category' => 'notifications.categories.local_invoices',
        'roles' => ['supplier'],
        'supplier_scopes' => ['local'],
        'default' => true,
    ],
    'local_invoice_refund_settled' => [
        'class' => SystemNotification::class,
        'source_event' => 'local_invoice.refund_settled',
        'label' => 'notifications.events.local_invoice_refund_settled.label',
        'description' => 'notifications.events.local_invoice_refund_settled.description',
        'category' => 'notifications.categories.local_invoices',
        'roles' => ['supplier'],
        'supplier_scopes' => ['local'],
        'default' => true,
    ],
    'local_invoice_physical_delivery_reminder' => [
        'class' => SystemNotification::class,
        'source_event' => 'local_invoice.physical_delivery_reminder',
        'label' => 'notifications.events.local_invoice_physical_delivery_reminder.label',
        'description' => 'notifications.events.local_invoice_physical_delivery_reminder.description',
        'category' => 'notifications.categories.local_invoices',
        'roles' => ['supplier'],
        'supplier_scopes' => ['local'],
        'default' => true,
        'priority' => 'action_required',
    ],
    'supplier_registration_submitted' => [
        'class' => SystemNotification::class,
        'source_event' => 'supplier_registration.submitted',
        'label' => 'notifications.events.supplier_registration_submitted.label',
        'description' => 'notifications.events.supplier_registration_submitted.description',
        'category' => 'notifications.categories.registration',
        'roles' => ['admin', 'finance', 'purchasing'],
        'supplier_scopes' => [],
        'default' => true,
        'priority' => 'action_required',
    ],
    'supplier_registration_resubmitted' => [
        'class' => SystemNotification::class,
        'source_event' => 'supplier_registration.resubmitted',
        'label' => 'notifications.events.supplier_registration_resubmitted.label',
        'description' => 'notifications.events.supplier_registration_resubmitted.description',
        'category' => 'notifications.categories.registration',
        'roles' => ['admin', 'finance', 'purchasing'],
        'supplier_scopes' => [],
        'default' => true,
        'priority' => 'action_required',
    ],
    'supplier_registration_revision_requested' => [
        'class' => SystemNotification::class,
        'source_event' => 'supplier_registration.revision_requested',
        'label' => 'notifications.events.supplier_registration_revision_requested.label',
        'description' => 'notifications.events.supplier_registration_revision_requested.description',
        'category' => 'notifications.categories.registration',
        'roles' => ['admin', 'finance', 'purchasing'],
        'supplier_scopes' => [],
        'default' => true,
    ],
    'supplier_registration_rejected' => [
        'class' => SystemNotification::class,
        'source_event' => 'supplier_registration.rejected',
        'label' => 'notifications.events.supplier_registration_rejected.label',
        'description' => 'notifications.events.supplier_registration_rejected.description',
        'category' => 'notifications.categories.registration',
        'roles' => ['admin', 'finance', 'purchasing'],
        'supplier_scopes' => [],
        'default' => true,
    ],
    'supplier_registration_approved' => [
        'class' => SystemNotification::class,
        'source_event' => 'supplier_registration.approved',
        'label' => 'notifications.events.supplier_registration_approved.label',
        'description' => 'notifications.events.supplier_registration_approved.description',
        'category' => 'notifications.categories.registration',
        'roles' => ['admin', 'finance', 'purchasing'],
        'supplier_scopes' => [],
        'default' => true,
    ],
    'supplier_audit_assigned' => [
        'class' => SystemNotification::class,
        'source_event' => 'supplier_audit.assigned',
        'label' => 'notifications.events.supplier_audit_assigned.label',
        'description' => 'notifications.events.supplier_audit_assigned.description',
        'category' => 'notifications.categories.supplier_audits',
        'roles' => ['supplier'],
        'supplier_scopes' => ['local'],
        'default' => true,
    ],
    'supplier_audit_revision_requested' => [
        'class' => SystemNotification::class,
        'source_event' => 'supplier_audit.revision_requested',
        'label' => 'notifications.events.supplier_audit_revision_requested.label',
        'description' => 'notifications.events.supplier_audit_revision_requested.description',
        'category' => 'notifications.categories.supplier_audits',
        'roles' => ['supplier'],
        'supplier_scopes' => ['local'],
        'default' => true,
        'priority' => 'action_required',
    ],
    'supplier_audit_result_published' => [
        'class' => SystemNotification::class,
        'source_event' => 'supplier_audit.result_published',
        'label' => 'notifications.events.supplier_audit_result_published.label',
        'description' => 'notifications.events.supplier_audit_result_published.description',
        'category' => 'notifications.categories.supplier_audits',
        'roles' => ['supplier'],
        'supplier_scopes' => ['local'],
        'default' => true,
    ],
    'supplier_audit_cancelled' => [
        'class' => SystemNotification::class,
        'source_event' => 'supplier_audit.cancelled',
        'label' => 'notifications.events.supplier_audit_cancelled.label',
        'description' => 'notifications.events.supplier_audit_cancelled.description',
        'category' => 'notifications.categories.supplier_audits',
        'roles' => ['supplier'],
        'supplier_scopes' => ['local'],
        'default' => true,
    ],
    'supplier_audit_deadline_changed' => [
        'class' => SystemNotification::class,
        'source_event' => 'supplier_audit.deadline_changed',
        'label' => 'notifications.events.supplier_audit_deadline_changed.label',
        'description' => 'notifications.events.supplier_audit_deadline_changed.description',
        'category' => 'notifications.categories.supplier_audits',
        'roles' => ['supplier'],
        'supplier_scopes' => ['local'],
        'default' => true,
    ],
    'supplier_audit_invoice_blocked' => [
        'class' => SystemNotification::class,
        'source_event' => 'supplier_audit.invoice_blocked',
        'label' => 'notifications.events.supplier_audit_invoice_blocked.label',
        'description' => 'notifications.events.supplier_audit_invoice_blocked.description',
        'category' => 'notifications.categories.supplier_audits',
        'roles' => ['supplier'],
        'supplier_scopes' => ['local'],
        'default' => true,
        'priority' => 'action_required',
    ],
    'supplier_audit_submitted' => [
        'class' => SystemNotification::class,
        'source_event' => 'supplier_audit.submitted',
        'label' => 'notifications.events.supplier_audit_submitted.label',
        'description' => 'notifications.events.supplier_audit_submitted.description',
        'category' => 'notifications.categories.supplier_audits',
        'roles' => ['purchasing'],
        'supplier_scopes' => [],
        'default' => true,
        'priority' => 'action_required',
    ],
    'export_completed' => [
        'class' => SystemNotification::class,
        'source_event' => 'export.completed',
        'label' => 'notifications.events.export_completed.label',
        'description' => 'notifications.events.export_completed.description',
        'category' => 'notifications.categories.exports',
        'roles' => ['admin', 'purchasing', 'qc', 'finance', 'accounting', 'ga', 'supplier'],
        'supplier_scopes' => [],
        'default' => true,
        'eligibility' => 'export_owner',
    ],
    'export_failed' => [
        'class' => SystemNotification::class,
        'source_event' => 'export.failed',
        'label' => 'notifications.events.export_failed.label',
        'description' => 'notifications.events.export_failed.description',
        'category' => 'notifications.categories.exports',
        'roles' => ['admin', 'purchasing', 'qc', 'finance', 'accounting', 'ga', 'supplier'],
        'supplier_scopes' => [],
        'default' => true,
        'eligibility' => 'export_owner',
    ],
    'new_device_login' => [
        'class' => SystemNotification::class,
        'source_event' => 'new_device_login',
        'label' => 'notifications.events.new_device_login.label',
        'description' => 'notifications.events.new_device_login.description',
        'category' => 'notifications.categories.security',
        'roles' => ['admin', 'purchasing', 'supplier', 'qc', 'accounting', 'finance', 'ga'],
        'supplier_scopes' => [],
        'default' => true,
        'priority' => 'action_required',
    ],
    'repeated_lockouts_detected' => [
        'class' => SystemNotification::class,
        'source_event' => 'repeated_lockouts_detected',
        'label' => 'notifications.events.repeated_lockouts_detected.label',
        'description' => 'notifications.events.repeated_lockouts_detected.description',
        'category' => 'notifications.categories.security',
        'roles' => ['admin'],
        'supplier_scopes' => [],
        'default' => true,
        'priority' => 'action_required',
    ],
];
