<?php

return [
    'audiences' => [
        'admin' => [
            'admin.dashboard' => [
                'label' => 'Dashboard',
                'icon' => 'gauge',
                'route' => 'admin.dashboard',
                'active' => 'admin.dashboard',
            ],
            'admin.users' => [
                'label' => 'Users',
                'icon' => 'users',
                'route' => 'admin.users.index',
                'active' => 'admin.users.*',
            ],
            'admin.registrations' => [
                'label' => 'Supplier Registrations',
                'icon' => 'user-plus',
                'route' => 'supplier-registrations.index',
                'active' => 'supplier-registrations.*',
            ],
            'admin.exchange-rates' => [
                'label' => 'Exchange Rates',
                'icon' => 'badge-dollar-sign',
                'route' => 'admin.exchange-rates.index',
                'active' => 'admin.exchange-rates.*',
            ],
            'admin.materials' => [
                'label' => 'Materials and HS Code',
                'icon' => 'boxes',
                'route' => 'admin.material-hs-code.index',
                'active' => 'admin.material-hs-code.*',
            ],
            'admin.audit' => [
                'label' => 'Authentication Audit',
                'icon' => 'shield-check',
                'route' => 'admin.auth-audit-logs.index',
                'active' => 'admin.auth-audit-logs.*',
            ],
            'admin.announcements' => [
                'label' => 'Announcements',
                'icon' => 'megaphone',
                'route' => 'admin.announcements.index',
                'active' => 'admin.announcements.*',
            ],
        ],
        'purchasing' => [
            'purchasing.dashboard' => [
                'label' => 'Dashboard',
                'icon' => 'gauge',
                'route' => 'purchasing.dashboard',
                'active' => 'purchasing.dashboard',
            ],
            'purchasing.periods' => [
                'label' => 'Period Management',
                'icon' => 'calendar-days',
                'route' => 'purchasing.periods.index',
                'active' => 'purchasing.periods.*',
                'purchasing_list' => true,
            ],
            'purchasing.requisitions' => [
                'label' => 'Purchase Requisition',
                'icon' => 'clipboard-list',
                'route' => 'purchasing.requisitions.index',
                'active' => 'purchasing.requisitions.*',
                'purchasing_list' => true,
            ],
            'purchasing.registrations' => [
                'label' => 'Supplier Registrations',
                'icon' => 'user-plus',
                'route' => 'supplier-registrations.index',
                'active' => 'supplier-registrations.*',
            ],
            'purchasing.quotations' => [
                'label' => 'Quotation',
                'icon' => 'tags',
                'route' => 'purchasing.quotations.index',
                'active' => 'purchasing.quotations.*',
                'purchasing_list' => true,
            ],
            'purchasing.comparison' => [
                'label' => 'Price Comparison',
                'icon' => 'chart-no-axes-combined',
                'route' => 'purchasing.comparison.inter-supplier',
                'active' => 'purchasing.comparison.*',
                'purchasing_list' => true,
            ],
            'purchasing.orders' => [
                'label' => 'Purchase Order',
                'icon' => 'receipt',
                'route' => 'purchasing.purchase-orders.index',
                'active' => 'purchasing.purchase-orders.*',
                'purchasing_list' => true,
            ],
            'purchasing.shipments' => [
                'label' => 'Shipments and Logistics',
                'icon' => 'truck',
                'route' => 'purchasing.shipments.index',
                'active' => 'purchasing.shipments.*',
                'purchasing_list' => true,
            ],
            'purchasing.local-vendors' => [
                'label' => 'Local Vendors',
                'icon' => 'building-2',
                'route' => 'purchasing.local-vendors.index',
                'active' => 'purchasing.local-vendors.*',
                'purchasing_list' => true,
            ],
            'purchasing.local-procurement' => [
                'label' => 'Local PO and GR',
                'icon' => 'package-check',
                'route' => 'purchasing.local-procurement.index',
                'active' => 'purchasing.local-procurement.*',
                'purchasing_list' => true,
            ],
            'purchasing.drp-supplier' => [
                'label' => 'DRP Supplier',
                'icon' => 'wallet',
                'route' => 'purchasing.drp.supplier',
                'active' => 'purchasing.drp.supplier',
                'purchasing_list' => true,
            ],
            'purchasing.drp-ga' => [
                'label' => 'DRP GA',
                'icon' => 'credit-card',
                'route' => 'purchasing.drp.ga',
                'active' => 'purchasing.drp.ga',
                'purchasing_list' => true,
            ],
            'purchasing.drp-paid' => [
                'label' => 'DRP Paid',
                'icon' => 'badge-check',
                'route' => 'purchasing.drp.paid.index',
                'active' => 'purchasing.drp.paid.*',
                'purchasing_list' => true,
            ],
            'purchasing.conversations' => [
                'label' => 'Negotiation and Chat',
                'icon' => 'message-circle-more',
                'route' => 'purchasing.conversations.index',
                'active' => 'purchasing.conversations.*',
                'purchasing_list' => true,
            ],
            'purchasing.claims' => [
                'label' => 'Material Claim',
                'icon' => 'shield-alert',
                'route' => 'purchasing.claims.index',
                'active' => 'purchasing.claims.*',
                'purchasing_list' => true,
            ],
            'purchasing.reports' => [
                'label' => 'Report',
                'icon' => 'file-chart-column',
                'route' => 'purchasing.reports.index',
                'active' => 'purchasing.reports.*',
                'purchasing_list' => true,
            ],
            'purchasing.exports' => [
                'label' => 'Export History',
                'icon' => 'file-spreadsheet',
                'route' => 'exports.index',
                'active' => 'exports.*',
            ],
        ],
        'supplier' => [
            'local' => [
                'supplier_local.dashboard' => [
                    'label' => 'Dashboard',
                    'icon' => 'gauge',
                    'route' => 'local-supplier.dashboard',
                    'active' => 'local-supplier.dashboard',
                ],
                'supplier_local.invoice-create' => [
                    'label' => 'Ajukan Invoice',
                    'icon' => 'file-plus',
                    'route' => 'local-supplier.invoices.create',
                    'active' => 'local-supplier.invoices.create',
                ],
                'supplier_local.invoices' => [
                    'label' => 'Daftar Invoice',
                    'icon' => 'receipt',
                    'route' => 'local-supplier.invoices.index',
                    'active' => 'local-supplier.invoices.*',
                ],
                'supplier_local.orders' => [
                    'label' => 'Purchase Orders',
                    'icon' => 'package-check',
                    'route' => 'local-supplier.purchase-orders.index',
                    'active' => 'local-supplier.purchase-orders.*',
                ],
                'supplier_local.vendor-profile' => [
                    'label' => 'Profil Vendor',
                    'icon' => 'building-2',
                    'route' => 'local-supplier.vendor-profile.show',
                    'active' => 'local-supplier.vendor-profile.*',
                ],
                'supplier_local.information' => [
                    'label' => 'Pengumuman',
                    'icon' => 'info',
                    'route' => 'local-supplier.information',
                    'active' => 'local-supplier.information',
                ],
            ],
            'import' => [
                'supplier_import.dashboard' => [
                    'label' => 'Dashboard',
                    'icon' => 'gauge',
                    'route' => 'supplier.dashboard',
                    'active' => 'supplier.dashboard',
                ],
                'supplier_import.quotations' => [
                    'label' => 'Quotation Period',
                    'icon' => 'calendar-days',
                    'route' => 'supplier.quotations.index',
                    'active' => 'supplier.quotations.*',
                ],
                'supplier_import.orders' => [
                    'label' => 'Purchase Order',
                    'icon' => 'receipt',
                    'route' => 'supplier.purchase-orders.index',
                    'active' => 'supplier.purchase-orders.*',
                ],
                'supplier_import.shipments' => [
                    'label' => 'Shipments and Deliveries',
                    'icon' => 'truck',
                    'route' => 'supplier.shipments.index',
                    'active' => 'supplier.shipments.*',
                ],
                'supplier_import.conversations' => [
                    'label' => 'Negotiation and Chat',
                    'icon' => 'message-circle-more',
                    'route' => 'supplier.conversations.index',
                    'active' => 'supplier.conversations.*',
                ],
                'supplier_import.claims' => [
                    'label' => 'Material Claim',
                    'icon' => 'shield-alert',
                    'route' => 'supplier.claims.index',
                    'active' => 'supplier.claims.*',
                ],
                'supplier_import.price-history' => [
                    'label' => 'Price History',
                    'icon' => 'trending-up',
                    'route' => 'supplier.price-history.index',
                    'active' => 'supplier.price-history.*',
                ],
                'supplier_import.exports' => [
                    'label' => 'Export History',
                    'icon' => 'file-spreadsheet',
                    'route' => 'exports.index',
                    'active' => 'exports.*',
                ],
                'supplier_import.announcements' => [
                    'label' => 'ADASI Information',
                    'icon' => 'info',
                    'route' => 'supplier.announcements.index',
                    'active' => 'supplier.announcements.*',
                ],
            ],
        ],
        'finance' => [
            'finance.dashboard' => [
                'label' => 'Dashboard',
                'icon' => 'gauge',
                'route' => 'finance.dashboard',
                'active' => 'finance.dashboard',
            ],
            'finance.invoices' => [
                'label' => 'Invoice Register',
                'icon' => 'receipt',
                'route' => 'finance.invoices.index',
                'active' => 'finance.invoices.*',
            ],
            'finance.ga-claims' => [
                'label' => 'Klaim GA',
                'icon' => 'file-text',
                'route' => 'finance.ga-claims.index',
                'active' => 'finance.ga-claims.*',
            ],
            'finance.drp-supplier' => [
                'label' => 'DRP Supplier',
                'icon' => 'wallet',
                'route' => 'finance.drp.supplier',
                'active' => ['finance.drp.supplier', 'finance.drp.show'],
            ],
            'finance.drp-ga' => [
                'label' => 'DRP GA',
                'icon' => 'credit-card',
                'route' => 'finance.drp.ga',
                'active' => 'finance.drp.ga',
            ],
            'finance.drp-paid' => [
                'label' => 'DRP Paid',
                'icon' => 'badge-check',
                'route' => 'finance.drp.paid.index',
                'active' => 'finance.drp.paid.*',
            ],
            'finance.overpayments' => [
                'label' => 'Supplier Overpayment',
                'icon' => 'circle-dollar-sign',
                'route' => 'finance.overpayments.index',
                'active' => 'finance.overpayments.*',
            ],
            'finance.registrations' => [
                'label' => 'Supplier Registrations',
                'icon' => 'user-plus',
                'route' => 'supplier-registrations.index',
                'active' => 'supplier-registrations.*',
            ],
            'finance.local-procurement' => [
                'label' => 'Master PO and GR',
                'icon' => 'package-check',
                'route' => 'finance.local-procurement.index',
                'active' => 'finance.local-procurement.*',
            ],
            'finance.master-invoices' => [
                'label' => 'Master Invoices',
                'icon' => 'database',
                'route' => 'finance.master-invoices',
                'active' => 'finance.master-invoices',
            ],
            'finance.vendor-master' => [
                'label' => 'Master Vendor',
                'icon' => 'building-2',
                'route' => 'finance.vendor-master.index',
                'active' => 'finance.vendor-master.*',
            ],
            'finance.exports' => [
                'label' => 'Export History',
                'icon' => 'file-spreadsheet',
                'route' => 'exports.index',
                'active' => 'exports.*',
            ],
        ],
        'accounting' => [
            'accounting.dashboard' => [
                'label' => 'Dashboard',
                'icon' => 'gauge',
                'route' => 'accounting.dashboard',
                'active' => 'accounting.dashboard',
            ],
            'accounting.invoices' => [
                'label' => 'Invoice Register',
                'icon' => 'receipt',
                'route' => 'accounting.invoices.index',
                'active' => 'accounting.invoices.*',
            ],
            'accounting.physical-verification' => [
                'label' => 'Physical Verification',
                'icon' => 'clipboard-check',
                'route' => 'accounting.physical-verification',
                'active' => 'accounting.physical-verification',
            ],
            'accounting.payment-schedule' => [
                'label' => 'Payment Schedule',
                'icon' => 'calendar-days',
                'route' => 'accounting.payment-schedule',
                'active' => 'accounting.payment-schedule',
            ],
            'accounting.reports' => [
                'label' => 'Reports',
                'icon' => 'file-chart-column',
                'route' => 'accounting.reports',
                'active' => 'accounting.reports*',
            ],
            'accounting.exports' => [
                'label' => 'Export History',
                'icon' => 'file-spreadsheet',
                'route' => 'exports.index',
                'active' => 'exports.*',
            ],
        ],
        'ga' => [
            'ga.dashboard' => [
                'label' => 'Dashboard',
                'icon' => 'gauge',
                'route' => 'ga.dashboard',
                'active' => 'ga.dashboard',
            ],
            'ga.claims' => [
                'label' => 'GA Claims',
                'icon' => 'receipt',
                'route' => 'ga.claims.index',
                'active' => ['ga.claims.index', 'ga.claims.show', 'ga.claims.receipt'],
            ],
            'ga.claim-create' => [
                'label' => 'Submit Claim',
                'icon' => 'file-plus',
                'route' => 'ga.claims.create',
                'active' => 'ga.claims.create',
            ],
            'ga.employees' => [
                'label' => 'Employee Master',
                'icon' => 'users',
                'route' => 'ga.employees.index',
                'active' => 'ga.employees.*',
            ],
            'ga.drp-draft' => [
                'label' => 'DRP GA Draft',
                'icon' => 'wallet',
                'route' => 'ga.drp-draft',
                'active' => 'ga.drp-draft*',
            ],
        ],
        'qc' => [
            'qc.dashboard' => [
                'label' => 'Dashboard',
                'icon' => 'gauge',
                'route' => 'qc.dashboard',
                'active' => 'qc.dashboard',
            ],
            'qc.inspections' => [
                'label' => 'QC Inspection',
                'icon' => 'clipboard-check',
                'route' => 'qc.inspections.index',
                'active' => 'qc.inspections.*',
            ],
            'qc.exports' => [
                'label' => 'Export History',
                'icon' => 'file-spreadsheet',
                'route' => 'exports.index',
                'active' => 'exports.*',
            ],
        ],
    ],
];
